### ISSUE TITLE
[BUG][PICO][3.x] export apk to pico neo3 will be not render! it is black screen

### ISSUE THREAD

**Issue by RubyKiss** [GodotVR/godot_openxr_vendors#225] opened 2024-11-06 11:45 UTC
and the Is it true that version 2.x does not allow you to control the game with a joystick?

**Comment by dsnopek** [comment] 2024-11-06 14:06
This sounds like a duplicate of https://github.com/GodotVR/godot_openxr_vendors/issues/201

> and the Is it true that version 2.x does not allow you to control the game with a joystick?

No, this plugin shouldn't have any effect on input. Most of OpenXR support is built in to Godot itself - this plugin only provides the Android loader and some vendor extensions to OpenXR.

If the 2.x version of this plugin is working for you on the Pico Neo 3, please let us know in a comment on the other issue! None of the maintainers have that headset, so we have to rely on user testing to let us know what works and what doesn't.

**Closed by dsnopek** 2024-11-06 14:06 UTC
