### ISSUE TITLE
grip_touch controller signal not happening on Quest2 and Pico4

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot_openxr_vendors#57] opened 2023-11-17 18:07 UTC
The XRPositionalTracker.button_pressed signal never emits a "grip_touch" touch event on the Quest2 or Pico4.  

It's detecting all the other button touches in clicks in my benchmark example.  

See the picture where I'm holding the trigger and grip buttons fully in (hence the input_float_changed is registering 1 on both of them).   

![image](https://github.com/GodotVR/godot_openxr_vendors/assets/677254/6a1c3345-3c27-4842-83f4-f2df2231dc13)

My working demo is at:
    https://github.com/goatchurchprime/godot-demo-projects/tree/openxr_seeallfeatures/xr/OpenXRHandTrackingDemo

**Comment by goatchurchprime** [comment] 2023-11-17 18:17
The same code is giving me `xr_interface.xr_play_area_mode = 0` and `xr_interface.get_play_area() = [ ]`.  I'll file this as another ticket if it helps.  (I haven't checked it on the Rift yet)

**Comment by BastiaanOlij** [comment] 2023-11-18 09:10
Ok, so this is not a bug, it's supposed to work this way.

Remember the default action map is just there to mimic the behaviour we have in Godot 3. It presents each input on the controller as an input for Godot, 1:1.

That means that an action will only work, if the action is mapped to an input.  And action is only mapped to an input in the default map, if the input exists on the controller.

We can't magically make features of a controller appear that aren't there.

On an index we see all grip related actions mapped:
![image](https://github.com/GodotVR/godot_openxr_vendors/assets/1945449/29f2ec7c-a727-4897-90a4-d28997f42005)

While on the Quest no such input:
![image](https://github.com/GodotVR/godot_openxr_vendors/assets/1945449/651b7a3e-a4da-42ed-a6fb-d6609af83a30)

This is the danger of mapping inputs 1:1 and really how the action map isn't supposed to be used. You should create an action map for your game with the actions your game needs, and then map the available inputs accordingly.
Even then it is possible you use a controller that doesn't have the required inputs for your game of instance:
-  WMR controllers or original Vive wands that don't have A/B/X/Y buttons,
-  WMR controllers and index controllers have both touchpad and joystick, while others only have one or the other,
So if you're game relies on one of those to function, you're in trouble. 

For XR Tools this for instance means that we should create our own XR Tools action map. We didn't because for a long time we wanted to keep compatibility between Godot 3 and Godot 4, and now it's a major breaking change. But officially we should have actions for each feature, and map them to the required buttons in the action map, instead of selecting the action from a dropdown on the function.

So say for our jump function, instead of having:
![image](https://github.com/GodotVR/godot_openxr_vendors/assets/1945449/8f7feba3-b088-431c-9e83-025088738a48)

We should remove the "Jump Button Action" and instead have an action called "Jump" in the action map, and have that action mapped to the best input on each controller. Right now jump is not possible on for instance a WMR controller because there is no A/X button on those devices, but when using actions properly, we could map the Jump action to one of the touchpad corners (it can function as a D-pad, though we need to implement an extension for that).

To be exact, XR Tools completely breaks right now if a user decides to make their own action map and strays away from the actions XR Tools assumes are there.

**Comment by BastiaanOlij** [comment] 2023-11-18 09:12
Actually looking through all the profiles, I don't think any controllers even support touch on the grip button, only grip force which is only available on Index.

**Comment by BastiaanOlij** [comment] 2023-11-18 09:36
Removing the dud action here: https://github.com/godotengine/godot/pull/85048

**Comment by BastiaanOlij** [comment] 2024-05-16 08:26
Closing this issue as resolved through the above PR.

**Closed by BastiaanOlij** 2024-05-16 08:26 UTC
